### PR TITLE
Fix some typos

### PR DESCRIPTION
**Pull request by henrikolsson**
This is the same as https://github.com/Bitmessage/PyBitmessage/pull/822

I've not used gpg with git before, i made a signed commit with the same change. Is it correctly done?

### CODE REVIEW

**Comment by PeterSurda** [comment]
I haven't dealt with a PGP signed pull request before either so I need to test it myself.

**Comment by PeterSurda** [comment]
Please upload your public key to a keyserver if you have not done so yet (I can't find it).

**Comment by henrikolsson** [comment]
It's available at http://keys.gnupg.net/ and https://keyserver.ubuntu.com/ now

**Comment by PeterSurda** [comment]
Ok it worked, I did it locally, but for some reason it does not automatically update the github pull request, so I'm closing it manually. Thank you.

**Comment by henrikolsson** [comment]
Nice, thanks

**Pull request closed without merging**
